In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

import seaborn as sns

In [ ]:
vocab  = corpus[0].split()
vocab.extend(corpus[1].split())
vocab = list(set(vocab))

In [ ]:

vocab = sorted(list(map(lambda x: x.lower(), vocab)))

In [ ]:
vocab

In [ ]:
corpus = ['Time flies flies like an arrow.',
          'Fruit flies like a banana.']

one_hot_vectorizer = CountVectorizer(binary=True)
one_hot = one_hot_vectorizer.fit_transform(corpus).toarray()

sns.heatmap(one_hot, annot=True, cbar=False,xticklabels = vocab,yticklabels=['Sentence 1','Sentence 2'])


In [ ]:
#TF-IDF - Term frequency and Inverse Document Frequency

In [ ]:
#Generating a TF-IDF representation using scikit-learn


from sklearn.feature_extraction.text import TfidfVectorizer
import seaborn as sns

tfidf_vectorizer = TfidfVectorizer()

tfidf = tfidf_vectorizer.fit_transform(corpus).toarray()
sns.heatmap(tfidf, annot=True, cbar=False, xticklabels=vocab, yticklabels=['Sentence 1', 'Senctence 2'])

Torch Tensors

In [ ]:
#create a helper function


def describe(x):
    print("Type: {}".format(x.type()))
    print(f"Shape/size: {x.shape}")
    print(f"Values: \n{x}")

In [ ]:
import torch
describe(torch.rand(2,3)) #uniform random
describe(torch.randn(2,3))
describe(torch.zeros(2,3))
x = torch.ones(2,3)
describe(x)
x.fill_(5)
describe(x)

Tensor Types and Size

In [ ]:
#1
x = torch.FloatTensor([[1,2,3],[4,5,6]])
describe(x)
#2 
x = x.long()
describe(x)
#3

x = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.int64)
describe(x)

In [ ]:
#4

x = x.float()
describe(x)
Tensor operations
x = torch.randn(2,3)
describe(x)
describe(torch.add(x,x))
describe(x +x)

In [ ]:
#arange
describe(torch.arange(6))

#view
x=  torch.arange(8).view(4,2)
describe(torch.arange(6).view(2,3))  #sort of reshaping the vector
describe(x)

In [ ]:
#If we want to do sum on columns

describe(torch.sum(x, dim=0))


#sum on rows

describe(torch.sum(x, dim=1))


#Also we can transpose the matrix

describe(x.T)

Indexing, slicing and joining

In [104]:
x[:-1,:2]

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [108]:
describe(x[0,1])
indices = torch.LongTensor([0,1])
describe(torch.index_select(x, dim=0, index=indices))
row_indices = torch.arange(2).long()
col_indices = torch.LongTensor([0,1])
describe(x[row_indices, col_indices])

Type: torch.LongTensor
Shape/size: torch.Size([])
Values: 
1


In [116]:
describe(torch.cat([x,x], dim=1))

Type: torch.LongTensor
Shape/size: torch.Size([4, 4])
Values: 
tensor([[0, 1, 0, 1],
        [2, 3, 2, 3],
        [4, 5, 4, 5],
        [6, 7, 6, 7]])


In [120]:
x2 = torch.ones(4,2)

In [124]:
x2[:,1] +=  1
describe(x2)

Type: torch.FloatTensor
Shape/size: torch.Size([4, 2])
Values: 
tensor([[1., 2.],
        [1., 2.],
        [1., 2.],
        [1., 2.]])


In [133]:
x = x.to(torch.float)

In [135]:
torch.matmul(x.T,x2)

tensor([[12., 24.],
        [16., 32.]])

torch.grad

In [136]:
x = torch.ones(2,2, requires_grad=True)
describe(x)
print(x.grad is None)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
True


In [137]:
y = (x+2) * (x + 5 ) + 3
describe(y)
print(x.grad is None)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)
True


In [138]:
z = y.mean()
describe(z)
z.backward()
print(x.grad is None)

Type: torch.FloatTensor
Shape/size: torch.Size([])
Values: 
21.0
False


In [142]:
print(torch.cuda.is_available())

False


In [145]:
#preffered method

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cpu


In [146]:
x=  torch.rand(3,3).to(device)

In [148]:
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([3, 3])
Values: 
tensor([[0.9940, 0.0627, 0.6759],
        [0.6710, 0.6265, 0.0485],
        [0.6748, 0.4083, 0.9273]])


In [149]:
y =torch.rand(3,3)

In [150]:
x + y

tensor([[1.2434, 1.0597, 0.8367],
        [0.7382, 0.7890, 0.4081],
        [1.3018, 0.7471, 1.5143]])

In [151]:
cpu_device = torch.device("cpu")
y =  y.to(cpu_device)
x=  x.to(cpu_device)
x + y

tensor([[1.2434, 1.0597, 0.8367],
        [0.7382, 0.7890, 0.4081],
        [1.3018, 0.7471, 1.5143]])

In [163]:
x1

tensor([[1., 1., 1.]])

In [167]:
'''Excercise 1'''
x1 = torch.ones(1,3)
x3 = torch.cat([x1,x],dim=0)

In [223]:

x3

#soln
a = torch.rand(3,3)
print(a.unsqueeze(0))


tensor([[[0.5412, 0.5398, 0.7735],
         [0.4175, 0.0113, 0.0829],
         [0.2578, 0.8875, 0.9758]]])


In [224]:
'''Excercise 2'''
x4 = x3[1:,:]
x4
#soln
x3.squeeze(0)

tensor([[1.0000, 1.0000, 1.0000],
        [1.9940, 0.0627, 0.6759],
        [1.6710, 0.6265, 0.0485],
        [1.6748, 0.4083, 0.9273]])

In [181]:
'''Excercise 3'''

random_tensor = torch.rand(5,3)
print(random_tensor)


#scale the tensor to the interval [3.7)

random_tensor*(7-3) + 3

tensor([[0.3442, 0.7396, 0.3404],
        [0.2918, 0.6985, 0.0326],
        [0.8454, 0.7098, 0.5792],
        [0.7247, 0.6935, 0.1599],
        [0.7464, 0.7485, 0.8887]])


tensor([[4.3767, 5.9583, 4.3614],
        [4.1672, 5.7940, 3.1306],
        [6.3816, 5.8392, 5.3167],
        [5.8987, 5.7739, 3.6394],
        [5.9855, 5.9940, 6.5550]])

In [200]:
'''Excercise 4'''
torch.randn(5,3)

tensor([[ 0.7622, -0.4842,  1.4043],
        [ 0.1890, -1.0304, -0.7397],
        [-0.5791,  0.4324,  1.4351],
        [ 1.4301,  1.0704, -0.5254],
        [-0.9871, -1.1784,  0.9174]])

In [209]:
'''Excercise5'''
tensor = torch.Tensor([1, 1, 1,0, 1])
tensor.nonzero()

tensor([[0],
        [1],
        [2],
        [4]])

In [225]:
'''Excercise 6'''
random_tensor =  torch.rand(3,1)
random_tensor = torch.cat([random_tensor,random_tensor,random_tensor,random_tensor],dim=1)
print(random_tensor)


#soln

random_tensor.expand(3,4)

tensor([[0.7106, 0.7106, 0.7106, 0.7106],
        [0.1328, 0.1328, 0.1328, 0.1328],
        [0.2998, 0.2998, 0.2998, 0.2998]])


tensor([[0.7106, 0.7106, 0.7106, 0.7106],
        [0.1328, 0.1328, 0.1328, 0.1328],
        [0.2998, 0.2998, 0.2998, 0.2998]])

In [ ]:
'''Excercise 7'''
a = torch.rand(3,4,5)
b = torch.rand(3,5,4)

torch.matmul(a,b)
print(a@b)
print(torch.bmm(a,b))

In [227]:
a = torch.rand(3, 4, 5)
b = torch.rand(5, 4)

print(a)
print(b)

tensor([[[0.2463, 0.9930, 0.0990, 0.0734, 0.0600],
         [0.2154, 0.7167, 0.0283, 0.5925, 0.9207],
         [0.8778, 0.3160, 0.2032, 0.1153, 0.8664],
         [0.0479, 0.1926, 0.3400, 0.7307, 0.6901]],

        [[0.4574, 0.8681, 0.1875, 0.5737, 0.7322],
         [0.7355, 0.1797, 0.3841, 0.8928, 0.3124],
         [0.1929, 0.1795, 0.2827, 0.3377, 0.9616],
         [0.8823, 0.9927, 0.2913, 0.5691, 0.7566]],

        [[0.2591, 0.9456, 0.2115, 0.0963, 0.7053],
         [0.0509, 0.3478, 0.4548, 0.7606, 0.8537],
         [0.1865, 0.1758, 0.0607, 0.5378, 0.1996],
         [0.6337, 0.8376, 0.4026, 0.1140, 0.0983]]])
tensor([[0.2675, 0.1769, 0.2959, 0.8983],
        [0.0909, 0.2884, 0.6650, 0.8755],
        [0.7599, 0.1950, 0.0254, 0.3132],
        [0.9176, 0.1922, 0.3857, 0.7361],
        [0.5165, 0.6735, 0.6489, 0.7713]])


In [231]:
a.size(0)

3

In [239]:
b.squeeze(0)

tensor([[0.2675, 0.1769, 0.2959, 0.8983],
        [0.0909, 0.2884, 0.6650, 0.8755],
        [0.7599, 0.1950, 0.0254, 0.3132],
        [0.9176, 0.1922, 0.3857, 0.7361],
        [0.5165, 0.6735, 0.6489, 0.7713]])

In [234]:
b.expand(a.size(0), *b.size())

tensor([[[0.2675, 0.1769, 0.2959, 0.8983],
         [0.0909, 0.2884, 0.6650, 0.8755],
         [0.7599, 0.1950, 0.0254, 0.3132],
         [0.9176, 0.1922, 0.3857, 0.7361],
         [0.5165, 0.6735, 0.6489, 0.7713]],

        [[0.2675, 0.1769, 0.2959, 0.8983],
         [0.0909, 0.2884, 0.6650, 0.8755],
         [0.7599, 0.1950, 0.0254, 0.3132],
         [0.9176, 0.1922, 0.3857, 0.7361],
         [0.5165, 0.6735, 0.6489, 0.7713]],

        [[0.2675, 0.1769, 0.2959, 0.8983],
         [0.0909, 0.2884, 0.6650, 0.8755],
         [0.7599, 0.1950, 0.0254, 0.3132],
         [0.9176, 0.1922, 0.3857, 0.7361],
         [0.5165, 0.6735, 0.6489, 0.7713]]])

In [228]:
torch.bmm(a, b.squeeze(0).expand(a.size(0), *b.size()))

tensor([[[0.3297, 0.4038, 0.8030, 1.2219],
         [1.1635, 0.9843, 1.3671, 1.9761],
         [0.9713, 0.8918, 1.0818, 1.8819],
         [1.3156, 0.7355, 0.8805, 1.3882]],

        [[1.2484, 0.9713, 1.4139, 2.2166],
         [1.4855, 0.6388, 0.8940, 1.8365],
         [1.0893, 0.8536, 0.9379, 1.4093],
         [1.4606, 1.1181, 1.6391, 2.7553]],

        [[0.7687, 0.8534, 1.2057, 1.7418],
         [1.5297, 0.9192, 1.1053, 1.7110],
         [0.7085, 0.3333, 0.5106, 0.8902],
         [0.7070, 0.5203, 0.8626, 1.5884]]])